//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PMC_Sparrow_DataEntities : DbContext
    {
        public PMC_Sparrow_DataEntities()
            : base("name=PMC_Sparrow_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rit_citizenOTPCount> rit_citizenOTPCount { get; set; }
        public virtual DbSet<tbl_document_mstr> tbl_document_mstr { get; set; }
        public virtual DbSet<tbl_document_upload> tbl_document_upload { get; set; }
        public virtual DbSet<tbl_license_detail_temp> tbl_license_detail_temp { get; set; }
        public virtual DbSet<tbl_license_details> tbl_license_details { get; set; }
        public virtual DbSet<tbl_license_mail> tbl_license_mail { get; set; }
        public virtual DbSet<tbl_license_mstr> tbl_license_mstr { get; set; }
        public virtual DbSet<tbl_ml_transaction_details> tbl_ml_transaction_details { get; set; }
    
        public virtual ObjectResult<citizenOTPCount_Result> citizenOTPCount(Nullable<long> mobile, Nullable<int> oTP, Nullable<System.DateTime> datetime, Nullable<int> maxSubmitAttempts, Nullable<int> cooldownPeriodMinutes, ObjectParameter result)
        {
            var mobileParameter = mobile.HasValue ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(long));
    
            var oTPParameter = oTP.HasValue ?
                new ObjectParameter("OTP", oTP) :
                new ObjectParameter("OTP", typeof(int));
    
            var datetimeParameter = datetime.HasValue ?
                new ObjectParameter("datetime", datetime) :
                new ObjectParameter("datetime", typeof(System.DateTime));
    
            var maxSubmitAttemptsParameter = maxSubmitAttempts.HasValue ?
                new ObjectParameter("maxSubmitAttempts", maxSubmitAttempts) :
                new ObjectParameter("maxSubmitAttempts", typeof(int));
    
            var cooldownPeriodMinutesParameter = cooldownPeriodMinutes.HasValue ?
                new ObjectParameter("cooldownPeriodMinutes", cooldownPeriodMinutes) :
                new ObjectParameter("cooldownPeriodMinutes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<citizenOTPCount_Result>("citizenOTPCount", mobileParameter, oTPParameter, datetimeParameter, maxSubmitAttemptsParameter, cooldownPeriodMinutesParameter, result);
        }
    
        public virtual ObjectResult<Nullable<int>> rit_checkCustomerdocument(string mobileNumber)
        {
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("mobileNumber", mobileNumber) :
                new ObjectParameter("mobileNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("rit_checkCustomerdocument", mobileNumberParameter);
        }
    
        public virtual ObjectResult<string> rit_checkForOTP(string designation, string phone, string ipaddress)
        {
            var designationParameter = designation != null ?
                new ObjectParameter("designation", designation) :
                new ObjectParameter("designation", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var ipaddressParameter = ipaddress != null ?
                new ObjectParameter("ipaddress", ipaddress) :
                new ObjectParameter("ipaddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("rit_checkForOTP", designationParameter, phoneParameter, ipaddressParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> rit_ConsumerLicenseApplication(string occupancy_type_id, string mobile_no, string firm_name, string consumer_Name, string father_name, string email_id, string address, string firm_type, string buss_owner_name, string business_detail, string holding_no, string sales_tax_no, Nullable<int> businessward_id, string business_address, Nullable<System.DateTime> dOE, string tin_no, string pan_no, string voter_id_no, Nullable<int> business_name, string businessSize, Nullable<int> license_duration, Nullable<decimal> total_Price)
        {
            var occupancy_type_idParameter = occupancy_type_id != null ?
                new ObjectParameter("occupancy_type_id", occupancy_type_id) :
                new ObjectParameter("occupancy_type_id", typeof(string));
    
            var mobile_noParameter = mobile_no != null ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(string));
    
            var firm_nameParameter = firm_name != null ?
                new ObjectParameter("firm_name", firm_name) :
                new ObjectParameter("firm_name", typeof(string));
    
            var consumer_NameParameter = consumer_Name != null ?
                new ObjectParameter("consumer_Name", consumer_Name) :
                new ObjectParameter("consumer_Name", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("email_id", email_id) :
                new ObjectParameter("email_id", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var firm_typeParameter = firm_type != null ?
                new ObjectParameter("firm_type", firm_type) :
                new ObjectParameter("firm_type", typeof(string));
    
            var buss_owner_nameParameter = buss_owner_name != null ?
                new ObjectParameter("buss_owner_name", buss_owner_name) :
                new ObjectParameter("buss_owner_name", typeof(string));
    
            var business_detailParameter = business_detail != null ?
                new ObjectParameter("business_detail", business_detail) :
                new ObjectParameter("business_detail", typeof(string));
    
            var holding_noParameter = holding_no != null ?
                new ObjectParameter("holding_no", holding_no) :
                new ObjectParameter("holding_no", typeof(string));
    
            var sales_tax_noParameter = sales_tax_no != null ?
                new ObjectParameter("sales_tax_no", sales_tax_no) :
                new ObjectParameter("sales_tax_no", typeof(string));
    
            var businessward_idParameter = businessward_id.HasValue ?
                new ObjectParameter("Businessward_id", businessward_id) :
                new ObjectParameter("Businessward_id", typeof(int));
    
            var business_addressParameter = business_address != null ?
                new ObjectParameter("business_address", business_address) :
                new ObjectParameter("business_address", typeof(string));
    
            var dOEParameter = dOE.HasValue ?
                new ObjectParameter("DOE", dOE) :
                new ObjectParameter("DOE", typeof(System.DateTime));
    
            var tin_noParameter = tin_no != null ?
                new ObjectParameter("tin_no", tin_no) :
                new ObjectParameter("tin_no", typeof(string));
    
            var pan_noParameter = pan_no != null ?
                new ObjectParameter("pan_no", pan_no) :
                new ObjectParameter("pan_no", typeof(string));
    
            var voter_id_noParameter = voter_id_no != null ?
                new ObjectParameter("voter_id_no", voter_id_no) :
                new ObjectParameter("voter_id_no", typeof(string));
    
            var business_nameParameter = business_name.HasValue ?
                new ObjectParameter("business_name", business_name) :
                new ObjectParameter("business_name", typeof(int));
    
            var businessSizeParameter = businessSize != null ?
                new ObjectParameter("BusinessSize", businessSize) :
                new ObjectParameter("BusinessSize", typeof(string));
    
            var license_durationParameter = license_duration.HasValue ?
                new ObjectParameter("license_duration", license_duration) :
                new ObjectParameter("license_duration", typeof(int));
    
            var total_PriceParameter = total_Price.HasValue ?
                new ObjectParameter("total_Price", total_Price) :
                new ObjectParameter("total_Price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("rit_ConsumerLicenseApplication", occupancy_type_idParameter, mobile_noParameter, firm_nameParameter, consumer_NameParameter, father_nameParameter, email_idParameter, addressParameter, firm_typeParameter, buss_owner_nameParameter, business_detailParameter, holding_noParameter, sales_tax_noParameter, businessward_idParameter, business_addressParameter, dOEParameter, tin_noParameter, pan_noParameter, voter_id_noParameter, business_nameParameter, businessSizeParameter, license_durationParameter, total_PriceParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> rit_ConsumerMobile(string mobile, string consumerName, string iPAddress)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var consumerNameParameter = consumerName != null ?
                new ObjectParameter("ConsumerName", consumerName) :
                new ObjectParameter("ConsumerName", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("rit_ConsumerMobile", mobileParameter, consumerNameParameter, iPAddressParameter);
        }
    
        public virtual int rit_ConsumerRequestSave(string email, string propertyNo, Nullable<decimal> totalAmount, string iPAddress, string mobileNo)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var propertyNoParameter = propertyNo != null ?
                new ObjectParameter("PropertyNo", propertyNo) :
                new ObjectParameter("PropertyNo", typeof(string));
    
            var totalAmountParameter = totalAmount.HasValue ?
                new ObjectParameter("TotalAmount", totalAmount) :
                new ObjectParameter("TotalAmount", typeof(decimal));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rit_ConsumerRequestSave", emailParameter, propertyNoParameter, totalAmountParameter, iPAddressParameter, mobileNoParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> rit_CounterLicenseApplication(string occupancy_type_id, string mobile_no, string firm_name, string consumer_Name, string firm_type, string holding_no, Nullable<int> businessward_id, string business_address, Nullable<System.DateTime> dOE, Nullable<int> business_name, string businessSize, Nullable<int> license_duration, Nullable<decimal> total_Price)
        {
            var occupancy_type_idParameter = occupancy_type_id != null ?
                new ObjectParameter("occupancy_type_id", occupancy_type_id) :
                new ObjectParameter("occupancy_type_id", typeof(string));
    
            var mobile_noParameter = mobile_no != null ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(string));
    
            var firm_nameParameter = firm_name != null ?
                new ObjectParameter("firm_name", firm_name) :
                new ObjectParameter("firm_name", typeof(string));
    
            var consumer_NameParameter = consumer_Name != null ?
                new ObjectParameter("consumer_Name", consumer_Name) :
                new ObjectParameter("consumer_Name", typeof(string));
    
            var firm_typeParameter = firm_type != null ?
                new ObjectParameter("firm_type", firm_type) :
                new ObjectParameter("firm_type", typeof(string));
    
            var holding_noParameter = holding_no != null ?
                new ObjectParameter("holding_no", holding_no) :
                new ObjectParameter("holding_no", typeof(string));
    
            var businessward_idParameter = businessward_id.HasValue ?
                new ObjectParameter("Businessward_id", businessward_id) :
                new ObjectParameter("Businessward_id", typeof(int));
    
            var business_addressParameter = business_address != null ?
                new ObjectParameter("business_address", business_address) :
                new ObjectParameter("business_address", typeof(string));
    
            var dOEParameter = dOE.HasValue ?
                new ObjectParameter("DOE", dOE) :
                new ObjectParameter("DOE", typeof(System.DateTime));
    
            var business_nameParameter = business_name.HasValue ?
                new ObjectParameter("business_name", business_name) :
                new ObjectParameter("business_name", typeof(int));
    
            var businessSizeParameter = businessSize != null ?
                new ObjectParameter("BusinessSize", businessSize) :
                new ObjectParameter("BusinessSize", typeof(string));
    
            var license_durationParameter = license_duration.HasValue ?
                new ObjectParameter("license_duration", license_duration) :
                new ObjectParameter("license_duration", typeof(int));
    
            var total_PriceParameter = total_Price.HasValue ?
                new ObjectParameter("total_Price", total_Price) :
                new ObjectParameter("total_Price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("rit_CounterLicenseApplication", occupancy_type_idParameter, mobile_noParameter, firm_nameParameter, consumer_NameParameter, firm_typeParameter, holding_noParameter, businessward_idParameter, business_addressParameter, dOEParameter, business_nameParameter, businessSizeParameter, license_durationParameter, total_PriceParameter);
        }
    
        public virtual ObjectResult<rit_fetchConsumer_Result> rit_fetchConsumer(string mobileNo)
        {
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_fetchConsumer_Result>("rit_fetchConsumer", mobileNoParameter);
        }
    
        public virtual ObjectResult<rit_fetchConsumerdetail_Result> rit_fetchConsumerdetail(string mobileNo)
        {
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_fetchConsumerdetail_Result>("rit_fetchConsumerdetail", mobileNoParameter);
        }
    
        public virtual ObjectResult<rit_getBussinessAddressWard_Result> rit_getBussinessAddressWard(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_getBussinessAddressWard_Result>("rit_getBussinessAddressWard", pidParameter);
        }
    
        public virtual ObjectResult<rit_getConsumerData_Result> rit_getConsumerData(Nullable<long> mobileNo)
        {
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_getConsumerData_Result>("rit_getConsumerData", mobileNoParameter);
        }
    
        public virtual ObjectResult<rit_getConsumernamob_Result> rit_getConsumernamob(Nullable<long> mobile)
        {
            var mobileParameter = mobile.HasValue ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_getConsumernamob_Result>("rit_getConsumernamob", mobileParameter);
        }
    
        public virtual ObjectResult<rit_getConsumerPaymentForm_Result> rit_getConsumerPaymentForm(Nullable<long> mobileNo)
        {
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_getConsumerPaymentForm_Result>("rit_getConsumerPaymentForm", mobileNoParameter);
        }
    
        public virtual ObjectResult<rit_getConsumerPaymentReceipt_Result> rit_getConsumerPaymentReceipt(Nullable<long> mobileNo)
        {
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_getConsumerPaymentReceipt_Result>("rit_getConsumerPaymentReceipt", mobileNoParameter);
        }
    
        public virtual ObjectResult<rit_getCounterPaymentForm_Result> rit_getCounterPaymentForm(Nullable<long> mobileNo)
        {
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_getCounterPaymentForm_Result>("rit_getCounterPaymentForm", mobileNoParameter);
        }
    
        public virtual ObjectResult<rit_getCounterPaymentReceipt_Result> rit_getCounterPaymentReceipt(Nullable<long> mobileNo)
        {
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_getCounterPaymentReceipt_Result>("rit_getCounterPaymentReceipt", mobileNoParameter);
        }
    
        public virtual ObjectResult<string> rit_getDesignation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("rit_getDesignation");
        }
    
        public virtual ObjectResult<string> rit_getName(Nullable<long> mobileNumber)
        {
            var mobileNumberParameter = mobileNumber.HasValue ?
                new ObjectParameter("mobileNumber", mobileNumber) :
                new ObjectParameter("mobileNumber", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("rit_getName", mobileNumberParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> rit_getRateAccBusiness(Nullable<int> categoryID, Nullable<decimal> businessSize)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            var businessSizeParameter = businessSize.HasValue ?
                new ObjectParameter("businessSize", businessSize) :
                new ObjectParameter("businessSize", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("rit_getRateAccBusiness", categoryIDParameter, businessSizeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> rit_getTotalRate(Nullable<int> license_Year, Nullable<decimal> bussiness_size, Nullable<int> categoryID)
        {
            var license_YearParameter = license_Year.HasValue ?
                new ObjectParameter("License_Year", license_Year) :
                new ObjectParameter("License_Year", typeof(int));
    
            var bussiness_sizeParameter = bussiness_size.HasValue ?
                new ObjectParameter("bussiness_size", bussiness_size) :
                new ObjectParameter("bussiness_size", typeof(decimal));
    
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("rit_getTotalRate", license_YearParameter, bussiness_sizeParameter, categoryIDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> rit_SaveAgainConsumerLicenseApplication(string occupancy_type_id, string mobile_no, string firm_name, string consumer_Name, string father_name, string email_id, string address, string firm_type, string buss_owner_name, string business_detail, string holding_no, string sales_tax_no, Nullable<int> businessward_id, string business_address, Nullable<System.DateTime> dOE, string tin_no, string pan_no, string voter_id_no, Nullable<int> business_name, string businessSize, Nullable<int> license_duration, Nullable<decimal> total_Price, string application_no)
        {
            var occupancy_type_idParameter = occupancy_type_id != null ?
                new ObjectParameter("occupancy_type_id", occupancy_type_id) :
                new ObjectParameter("occupancy_type_id", typeof(string));
    
            var mobile_noParameter = mobile_no != null ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(string));
    
            var firm_nameParameter = firm_name != null ?
                new ObjectParameter("firm_name", firm_name) :
                new ObjectParameter("firm_name", typeof(string));
    
            var consumer_NameParameter = consumer_Name != null ?
                new ObjectParameter("consumer_Name", consumer_Name) :
                new ObjectParameter("consumer_Name", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("email_id", email_id) :
                new ObjectParameter("email_id", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var firm_typeParameter = firm_type != null ?
                new ObjectParameter("firm_type", firm_type) :
                new ObjectParameter("firm_type", typeof(string));
    
            var buss_owner_nameParameter = buss_owner_name != null ?
                new ObjectParameter("buss_owner_name", buss_owner_name) :
                new ObjectParameter("buss_owner_name", typeof(string));
    
            var business_detailParameter = business_detail != null ?
                new ObjectParameter("business_detail", business_detail) :
                new ObjectParameter("business_detail", typeof(string));
    
            var holding_noParameter = holding_no != null ?
                new ObjectParameter("holding_no", holding_no) :
                new ObjectParameter("holding_no", typeof(string));
    
            var sales_tax_noParameter = sales_tax_no != null ?
                new ObjectParameter("sales_tax_no", sales_tax_no) :
                new ObjectParameter("sales_tax_no", typeof(string));
    
            var businessward_idParameter = businessward_id.HasValue ?
                new ObjectParameter("Businessward_id", businessward_id) :
                new ObjectParameter("Businessward_id", typeof(int));
    
            var business_addressParameter = business_address != null ?
                new ObjectParameter("business_address", business_address) :
                new ObjectParameter("business_address", typeof(string));
    
            var dOEParameter = dOE.HasValue ?
                new ObjectParameter("DOE", dOE) :
                new ObjectParameter("DOE", typeof(System.DateTime));
    
            var tin_noParameter = tin_no != null ?
                new ObjectParameter("tin_no", tin_no) :
                new ObjectParameter("tin_no", typeof(string));
    
            var pan_noParameter = pan_no != null ?
                new ObjectParameter("pan_no", pan_no) :
                new ObjectParameter("pan_no", typeof(string));
    
            var voter_id_noParameter = voter_id_no != null ?
                new ObjectParameter("voter_id_no", voter_id_no) :
                new ObjectParameter("voter_id_no", typeof(string));
    
            var business_nameParameter = business_name.HasValue ?
                new ObjectParameter("business_name", business_name) :
                new ObjectParameter("business_name", typeof(int));
    
            var businessSizeParameter = businessSize != null ?
                new ObjectParameter("BusinessSize", businessSize) :
                new ObjectParameter("BusinessSize", typeof(string));
    
            var license_durationParameter = license_duration.HasValue ?
                new ObjectParameter("license_duration", license_duration) :
                new ObjectParameter("license_duration", typeof(int));
    
            var total_PriceParameter = total_Price.HasValue ?
                new ObjectParameter("total_Price", total_Price) :
                new ObjectParameter("total_Price", typeof(decimal));
    
            var application_noParameter = application_no != null ?
                new ObjectParameter("application_no", application_no) :
                new ObjectParameter("application_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("rit_SaveAgainConsumerLicenseApplication", occupancy_type_idParameter, mobile_noParameter, firm_nameParameter, consumer_NameParameter, father_nameParameter, email_idParameter, addressParameter, firm_typeParameter, buss_owner_nameParameter, business_detailParameter, holding_noParameter, sales_tax_noParameter, businessward_idParameter, business_addressParameter, dOEParameter, tin_noParameter, pan_noParameter, voter_id_noParameter, business_nameParameter, businessSizeParameter, license_durationParameter, total_PriceParameter, application_noParameter);
        }
    
        public virtual ObjectResult<rit_saveConsumerRequest_Result> rit_saveConsumerRequest(string mobileNo)
        {
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_saveConsumerRequest_Result>("rit_saveConsumerRequest", mobileNoParameter);
        }
    
        public virtual int rit_saveCounterCustomerdocument(string isMandatory, string documentType, string fileName, string mobileNumber, string ip_address, string doc_name)
        {
            var isMandatoryParameter = isMandatory != null ?
                new ObjectParameter("isMandatory", isMandatory) :
                new ObjectParameter("isMandatory", typeof(string));
    
            var documentTypeParameter = documentType != null ?
                new ObjectParameter("documentType", documentType) :
                new ObjectParameter("documentType", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("fileName", fileName) :
                new ObjectParameter("fileName", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("mobileNumber", mobileNumber) :
                new ObjectParameter("mobileNumber", typeof(string));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            var doc_nameParameter = doc_name != null ?
                new ObjectParameter("doc_name", doc_name) :
                new ObjectParameter("doc_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rit_saveCounterCustomerdocument", isMandatoryParameter, documentTypeParameter, fileNameParameter, mobileNumberParameter, ip_addressParameter, doc_nameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> rit_saveCounterdata(string iPAddress, Nullable<decimal> totalPrice, string fullName, string email, Nullable<long> mobileNo, string application_no)
        {
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var totalPriceParameter = totalPrice.HasValue ?
                new ObjectParameter("totalPrice", totalPrice) :
                new ObjectParameter("totalPrice", typeof(decimal));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            var application_noParameter = application_no != null ?
                new ObjectParameter("application_no", application_no) :
                new ObjectParameter("application_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("rit_saveCounterdata", iPAddressParameter, totalPriceParameter, fullNameParameter, emailParameter, mobileNoParameter, application_noParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> rit_saveCounterPaymentSuccess(string iPAddress, Nullable<decimal> totalPrice, string remarks, string paymentMode, string bank_name, string branch_name, Nullable<long> mobileNo, string application_no, string cheque_no, Nullable<System.DateTime> cheque_date)
        {
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var totalPriceParameter = totalPrice.HasValue ?
                new ObjectParameter("totalPrice", totalPrice) :
                new ObjectParameter("totalPrice", typeof(decimal));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            var paymentModeParameter = paymentMode != null ?
                new ObjectParameter("paymentMode", paymentMode) :
                new ObjectParameter("paymentMode", typeof(string));
    
            var bank_nameParameter = bank_name != null ?
                new ObjectParameter("bank_name", bank_name) :
                new ObjectParameter("bank_name", typeof(string));
    
            var branch_nameParameter = branch_name != null ?
                new ObjectParameter("branch_name", branch_name) :
                new ObjectParameter("branch_name", typeof(string));
    
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            var application_noParameter = application_no != null ?
                new ObjectParameter("application_no", application_no) :
                new ObjectParameter("application_no", typeof(string));
    
            var cheque_noParameter = cheque_no != null ?
                new ObjectParameter("cheque_no", cheque_no) :
                new ObjectParameter("cheque_no", typeof(string));
    
            var cheque_dateParameter = cheque_date.HasValue ?
                new ObjectParameter("cheque_date", cheque_date) :
                new ObjectParameter("cheque_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("rit_saveCounterPaymentSuccess", iPAddressParameter, totalPriceParameter, remarksParameter, paymentModeParameter, bank_nameParameter, branch_nameParameter, mobileNoParameter, application_noParameter, cheque_noParameter, cheque_dateParameter);
        }
    
        public virtual int rit_saveCustomerdocument(string isMandatory, string documentType, string fileName, string mobileNumber, string ip_address, string doc_name)
        {
            var isMandatoryParameter = isMandatory != null ?
                new ObjectParameter("isMandatory", isMandatory) :
                new ObjectParameter("isMandatory", typeof(string));
    
            var documentTypeParameter = documentType != null ?
                new ObjectParameter("documentType", documentType) :
                new ObjectParameter("documentType", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("fileName", fileName) :
                new ObjectParameter("fileName", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("mobileNumber", mobileNumber) :
                new ObjectParameter("mobileNumber", typeof(string));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            var doc_nameParameter = doc_name != null ?
                new ObjectParameter("doc_name", doc_name) :
                new ObjectParameter("doc_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rit_saveCustomerdocument", isMandatoryParameter, documentTypeParameter, fileNameParameter, mobileNumberParameter, ip_addressParameter, doc_nameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> rit_savePaymentFailure(string razorpay_order_id, string iPAddress, Nullable<decimal> totalPrice, string fullName, string email)
        {
            var razorpay_order_idParameter = razorpay_order_id != null ?
                new ObjectParameter("razorpay_order_id", razorpay_order_id) :
                new ObjectParameter("razorpay_order_id", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var totalPriceParameter = totalPrice.HasValue ?
                new ObjectParameter("totalPrice", totalPrice) :
                new ObjectParameter("totalPrice", typeof(decimal));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("rit_savePaymentFailure", razorpay_order_idParameter, iPAddressParameter, totalPriceParameter, fullNameParameter, emailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> rit_savePaymentSuccess(string razorpay_order_id, string iPAddress, Nullable<decimal> totalPrice, string fullName, string email, Nullable<long> mobileNo, string application_no)
        {
            var razorpay_order_idParameter = razorpay_order_id != null ?
                new ObjectParameter("razorpay_order_id", razorpay_order_id) :
                new ObjectParameter("razorpay_order_id", typeof(string));
    
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var totalPriceParameter = totalPrice.HasValue ?
                new ObjectParameter("totalPrice", totalPrice) :
                new ObjectParameter("totalPrice", typeof(decimal));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            var application_noParameter = application_no != null ?
                new ObjectParameter("application_no", application_no) :
                new ObjectParameter("application_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("rit_savePaymentSuccess", razorpay_order_idParameter, iPAddressParameter, totalPriceParameter, fullNameParameter, emailParameter, mobileNoParameter, application_noParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> rit_saveRTGSPaymentSuccess(string iPAddress, Nullable<decimal> totalPrice, string remarks, string paymentMode, string rTGSbankName, string rTGSbankBranch, Nullable<long> mobileNo, string application_no, string rTGSNo, Nullable<System.DateTime> rTGSDate)
        {
            var iPAddressParameter = iPAddress != null ?
                new ObjectParameter("IPAddress", iPAddress) :
                new ObjectParameter("IPAddress", typeof(string));
    
            var totalPriceParameter = totalPrice.HasValue ?
                new ObjectParameter("totalPrice", totalPrice) :
                new ObjectParameter("totalPrice", typeof(decimal));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            var paymentModeParameter = paymentMode != null ?
                new ObjectParameter("paymentMode", paymentMode) :
                new ObjectParameter("paymentMode", typeof(string));
    
            var rTGSbankNameParameter = rTGSbankName != null ?
                new ObjectParameter("RTGSbankName", rTGSbankName) :
                new ObjectParameter("RTGSbankName", typeof(string));
    
            var rTGSbankBranchParameter = rTGSbankBranch != null ?
                new ObjectParameter("RTGSbankBranch", rTGSbankBranch) :
                new ObjectParameter("RTGSbankBranch", typeof(string));
    
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            var application_noParameter = application_no != null ?
                new ObjectParameter("application_no", application_no) :
                new ObjectParameter("application_no", typeof(string));
    
            var rTGSNoParameter = rTGSNo != null ?
                new ObjectParameter("RTGSNo", rTGSNo) :
                new ObjectParameter("RTGSNo", typeof(string));
    
            var rTGSDateParameter = rTGSDate.HasValue ?
                new ObjectParameter("RTGSDate", rTGSDate) :
                new ObjectParameter("RTGSDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("rit_saveRTGSPaymentSuccess", iPAddressParameter, totalPriceParameter, remarksParameter, paymentModeParameter, rTGSbankNameParameter, rTGSbankBranchParameter, mobileNoParameter, application_noParameter, rTGSNoParameter, rTGSDateParameter);
        }
    
        public virtual ObjectResult<rit_SelectBusinessPremises_Result> rit_SelectBusinessPremises()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_SelectBusinessPremises_Result>("rit_SelectBusinessPremises");
        }
    
        public virtual ObjectResult<rit_SelectBusinessPremisesOwner_Result> rit_SelectBusinessPremisesOwner()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_SelectBusinessPremisesOwner_Result>("rit_SelectBusinessPremisesOwner");
        }
    
        public virtual ObjectResult<rit_SelectCategory_Result> rit_SelectCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_SelectCategory_Result>("rit_SelectCategory");
        }
    
        public virtual ObjectResult<rit_SelectFirmType_Result> rit_SelectFirmType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_SelectFirmType_Result>("rit_SelectFirmType");
        }
    
        public virtual ObjectResult<rit_SelectLisenceYear_Result> rit_SelectLisenceYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_SelectLisenceYear_Result>("rit_SelectLisenceYear");
        }
    
        public virtual ObjectResult<rit_Selectwardno_Result> rit_Selectwardno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_Selectwardno_Result>("rit_Selectwardno");
        }
    
        public virtual ObjectResult<rit_UpdateConsumerLicenseApplication_Result> rit_UpdateConsumerLicenseApplication(string application_no, Nullable<long> mobileNo)
        {
            var application_noParameter = application_no != null ?
                new ObjectParameter("application_no", application_no) :
                new ObjectParameter("application_no", typeof(string));
    
            var mobileNoParameter = mobileNo.HasValue ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rit_UpdateConsumerLicenseApplication_Result>("rit_UpdateConsumerLicenseApplication", application_noParameter, mobileNoParameter);
        }
    
        public virtual ObjectResult<SelectBusinessPremises_Result> SelectBusinessPremises()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectBusinessPremises_Result>("SelectBusinessPremises");
        }
    
        public virtual ObjectResult<SelectCategory_Result> SelectCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCategory_Result>("SelectCategory");
        }
    
        public virtual int UpdateCurrentPaymentReceipt(Nullable<int> pid, string sAS, string postingdate, string pAYMENTMODE, string paymentdate)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var sASParameter = sAS != null ?
                new ObjectParameter("SAS", sAS) :
                new ObjectParameter("SAS", typeof(string));
    
            var postingdateParameter = postingdate != null ?
                new ObjectParameter("postingdate", postingdate) :
                new ObjectParameter("postingdate", typeof(string));
    
            var pAYMENTMODEParameter = pAYMENTMODE != null ?
                new ObjectParameter("PAYMENTMODE", pAYMENTMODE) :
                new ObjectParameter("PAYMENTMODE", typeof(string));
    
            var paymentdateParameter = paymentdate != null ?
                new ObjectParameter("paymentdate", paymentdate) :
                new ObjectParameter("paymentdate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCurrentPaymentReceipt", pidParameter, sASParameter, postingdateParameter, pAYMENTMODEParameter, paymentdateParameter);
        }
    
        public virtual int UpdatePaymentReceipt(Nullable<int> pid, string rECEIPT_DATE, string pAYMENTMODE)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var rECEIPT_DATEParameter = rECEIPT_DATE != null ?
                new ObjectParameter("RECEIPT_DATE", rECEIPT_DATE) :
                new ObjectParameter("RECEIPT_DATE", typeof(string));
    
            var pAYMENTMODEParameter = pAYMENTMODE != null ?
                new ObjectParameter("PAYMENTMODE", pAYMENTMODE) :
                new ObjectParameter("PAYMENTMODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePaymentReceipt", pidParameter, rECEIPT_DATEParameter, pAYMENTMODEParameter);
        }
    }
}
