//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rit_citizenOTPCount
    {
        public int id { get; set; }
        public Nullable<long> citizen_mobile { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<System.DateTime> last_submit_time { get; set; }
        public Nullable<int> submit_attempts { get; set; }
    }
}
