//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_license_mstr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_license_mstr()
        {
            this.tbl_license_details = new HashSet<tbl_license_details>();
        }
    
        public long id { get; set; }
        public long ulb_id { get; set; }
        public long ward_id { get; set; }
        public string license_no { get; set; }
        public System.DateTime doe { get; set; }
        public string consumer_name { get; set; }
        public string father_name { get; set; }
        public Nullable<long> mobile_no { get; set; }
        public string email_id { get; set; }
        public string address { get; set; }
        public string firm_name { get; set; }
        public string bussiness_detail { get; set; }
        public string bussiness_address { get; set; }
        public Nullable<long> occupancy_type_id { get; set; }
        public string pan_no { get; set; }
        public string voter_id_no { get; set; }
        public string sales_tax_no { get; set; }
        public string holding_no { get; set; }
        public string tin_no { get; set; }
        public System.DateTime timestamp { get; set; }
        public long user_id { get; set; }
        public string status { get; set; }
        public Nullable<int> bussiness_name { get; set; }
        public string buss_owner_name { get; set; }
        public Nullable<int> applicant_ward_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_license_details> tbl_license_details { get; set; }
    }
}
