//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_document_upload
    {
        public long id { get; set; }
        public long ulb_id { get; set; }
        public long license_dtls_id { get; set; }
        public long doc_master_id { get; set; }
        public string file_name { get; set; }
        public string doc_upload_status { get; set; }
        public System.DateTime doc_upload_date { get; set; }
        public Nullable<System.DateTime> doc_varified_date { get; set; }
        public System.DateTime timestamp { get; set; }
        public long user_id { get; set; }
        public Nullable<int> doc_varified_status { get; set; }
        public string doc_reject_remarks { get; set; }
        public string ip_address { get; set; }
    
        public virtual tbl_document_mstr tbl_document_mstr { get; set; }
        public virtual tbl_license_details tbl_license_details { get; set; }
    }
}
