//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_license_mail
    {
        public long id { get; set; }
        public Nullable<long> license_dtls_id { get; set; }
        public Nullable<long> from_userid { get; set; }
        public Nullable<long> to_userid { get; set; }
        public Nullable<System.DateTime> stampdate { get; set; }
        public string remarks { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> user_id { get; set; }
        public string ip_address { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public Nullable<int> sign_status { get; set; }
    
        public virtual tbl_license_details tbl_license_details { get; set; }
    }
}
