//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_license_detail_temp
    {
        public long id { get; set; }
        public string owner_name { get; set; }
        public Nullable<long> mobile_no { get; set; }
        public string ip_address { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<int> ulb_id { get; set; }
        public Nullable<int> sts { get; set; }
    }
}
