//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ml_transaction_details
    {
        public long id { get; set; }
        public long transcation_mstr_id { get; set; }
        public long license_dtls_id { get; set; }
        public string cheque_no { get; set; }
        public Nullable<System.DateTime> cheque_date { get; set; }
        public string branch_name { get; set; }
        public string bank_name { get; set; }
        public Nullable<long> card_no { get; set; }
        public string card_holder_name { get; set; }
        public string card_type { get; set; }
        public decimal amount { get; set; }
        public string cheque_status { get; set; }
        public Nullable<System.DateTime> reconcile_date { get; set; }
        public string cleared_by { get; set; }
        public Nullable<System.DateTime> cleared_date { get; set; }
        public string remarks { get; set; }
        public Nullable<int> ulb_id { get; set; }
        public string ip_address { get; set; }
        public Nullable<long> user_id { get; set; }
    
        public virtual tbl_license_details tbl_license_details { get; set; }
    }
}
